#!/bin/bash

cdk synth

wait
# Define the path to the generated CloudFormation template
TEMPLATE_FILE="cdk.out/CdkProjectStack.template.json"

# Check if the file exists
if [ -f "$TEMPLATE_FILE" ]; then
  # Remove the BootstrapVersion parameter using jq
  jq 'del(.Parameters.BootstrapVersion)' "$TEMPLATE_FILE" > "$TEMPLATE_FILE.tmp" && mv "$TEMPLATE_FILE.tmp" "$TEMPLATE_FILE"
  echo "Removed BootstrapVersion parameter from the CloudFormation template."
  jq 'del(.Rules)' "$TEMPLATE_FILE" > "$TEMPLATE_FILE.tmp" && mv "$TEMPLATE_FILE.tmp" "$TEMPLATE_FILE"
  echo "Removed Rules from the CloudFormation template."
else
  echo "CloudFormation template not found. Make sure it has been generated by 'cdk synth'."
fi

aws cloudformation create-stack --stack-name AygoIaCWorkshop --template-body file://cdk.out/CdkProjectStack.template.json --capabilities CAPABILITY_IAM